[client]
showErrorDetails = false

[logger]
level = "error"

[server]
port = 8501
address = "0.0.0.0"
headless = true
enableXsrfProtection = false
enableCORS = true
runOnSave = false
fileWatcherType = "none"


